/**
 * Copyright (c) 2010-2022 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ai.coqui.libstt;

/**
 *
 * @author Dan Cunningham
 *
 */
public class SWIGTYPE_p_p_StreamingState {
    private transient long swigCPtr;

    protected SWIGTYPE_p_p_StreamingState(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
        swigCPtr = cPtr;
    }

    protected SWIGTYPE_p_p_StreamingState() {
        swigCPtr = 0;
    }

    protected static long getCPtr(SWIGTYPE_p_p_StreamingState obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected static long swigRelease(SWIGTYPE_p_p_StreamingState obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }
}
